"""Cinematic entry experience for Nyaya AI."""
from __future__ import annotations

import streamlit as st
import streamlit.components.v1 as components


def render() -> bool:
    """Show the landing experience while preserving the existing workspace flow."""
    st.markdown(
        """
        <style>
        [data-testid="stSidebar"], [data-testid="stHeader"], footer { display:none !important; }
        [data-testid="stAppViewContainer"] { background:#111b2b !important; }
        .block-container, [data-testid="stMainBlockContainer"] { max-width:none !important; padding:0 !important; }
        [data-testid="stMainBlockContainer"] > div { gap:0 !important; }
        .stButton { position:fixed !important; width:1px !important; height:1px !important; overflow:hidden !important; clip:rect(0 0 0 0) !important; clip-path:inset(50%) !important; white-space:nowrap !important; }
        </style>
        """,
        unsafe_allow_html=True,
    )
    components.html(_LANDING_HTML, height=800, scrolling=False)
    return st.button("Open Nyaya AI", key="landing_enter", type="primary")


_LANDING_HTML = r"""
<main id="landing">
  <canvas id="aurora" aria-hidden="true"></canvas>
  <div class="grain" aria-hidden="true"></div><div class="sunrise" aria-hidden="true"></div>
  <header class="nav">
    <a class="wordmark" href="#" aria-label="Nyaya AI home"><span class="mark"><i></i><i></i><i></i></span><span>NYĀYA</span><b>AI</b></a>
    <div class="nav-proof"><span></span> INDIA'S LEGAL INTELLIGENCE</div><div class="nav-rule"></div>
  </header>
  <section class="content">
    <div class="kicker"><span class="live-dot"></span><span>LEGAL CLARITY, DESIGNED FOR PEOPLE</span></div>
    <h1>Where every<br><em>voice</em> finds<br>its <span>due course.</span></h1>
    <p class="lede">Nyaya AI turns complex legal journeys into clear next steps, bringing calm, context and confidence to every matter.</p>
    <div class="motto"><span>सत्यमेव जयते</span><i></i><small>TRUTH ALONE TRIUMPHS</small></div>
    <div class="actions"><button id="enter" type="button"><span>ENTER NYĀYA</span><i>↗</i></button><span class="microcopy">START A MATTER<br>IN MINUTES</span></div>
  </section>
  <section class="statue-stage" aria-label="Lady Justice, an animated symbol of fair legal access">
    <div class="orbit orbit-back" aria-hidden="true"></div><div class="orbit orbit-front" aria-hidden="true"></div>
    <div class="gold-beam beam-one" aria-hidden="true"></div><div class="gold-beam beam-two" aria-hidden="true"></div><div class="halo" aria-hidden="true"></div>
    <div class="statue-card" id="statue-card"><div class="statue-shadow" aria-hidden="true"></div><img id="justice" src="/app/static/lady-justice-hero.png" alt="Lady Justice holding scales and a sword"><div class="scanline" aria-hidden="true"></div></div>
    <div class="focus-tag"><span class="focus-icon">✦</span><span>JUSTICE, WITH<br>HUMAN CONTEXT</span></div><div class="scale-tag"><i></i><span>BALANCE / <b>01</b></span></div>
  </section>
  <footer class="footer-line"><div><span>01</span> BEGIN WITH CLARITY</div><div class="footer-center">NYĀYA AI © 2026</div><div>THE RIGHT TO BE HEARD <span>↗</span></div></footer>
</main>
<style>
:root{--ink:#111b2b;--paper:#e7e1d4;--gold:#d7a54c;--gold-light:#f5d788;--orange:#e97835}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:var(--ink)}
#landing{isolation:isolate;position:relative;width:100%;height:800px;overflow:hidden;color:var(--paper);background:radial-gradient(ellipse 60% 76% at 78% 44%,#354961 0%,#20364f 29%,#182b43 52%,#111c2e 78%,#0d1727 100%);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#landing:before{content:"";position:absolute;z-index:-3;inset:0;opacity:.38;background:repeating-linear-gradient(115deg,transparent 0 62px,rgba(227,232,226,.04) 63px 64px,transparent 65px 127px)}#landing:after{content:"";position:absolute;z-index:-2;inset:0;background:linear-gradient(90deg,rgba(13,22,38,.53) 0%,rgba(15,27,44,.19) 36%,rgba(11,21,35,0) 69%),linear-gradient(0deg,rgba(7,15,26,.42),transparent 27%);pointer-events:none}
#aurora{position:absolute;z-index:-1;inset:0;width:100%;height:100%;opacity:.72}.grain{position:absolute;z-index:5;inset:0;pointer-events:none;opacity:.11;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.52'/%3E%3C/svg%3E");mix-blend-mode:soft-light}.sunrise{position:absolute;z-index:-1;width:670px;height:670px;right:-68px;top:74px;border-radius:50%;background:radial-gradient(circle,rgba(242,193,106,.25) 0,rgba(216,165,76,.12) 26%,rgba(53,100,134,.02) 60%,transparent 71%);filter:blur(3px);animation:breathe 7s ease-in-out infinite}@keyframes breathe{50%{transform:scale(1.09);opacity:.68}}
.nav{position:absolute;z-index:10;top:0;left:0;right:0;display:flex;align-items:center;height:93px;padding:0 clamp(26px,5.2vw,80px);border-bottom:1px solid rgba(229,224,211,.14)}.wordmark{display:flex;align-items:center;gap:10px;color:#f0eadf;text-decoration:none;font:800 16px/1 ui-sans-serif,system-ui,sans-serif;letter-spacing:.17em}.wordmark b{align-self:flex-start;color:var(--gold-light);font-size:8px;letter-spacing:.08em;margin-top:-2px}.mark{display:flex;align-items:flex-end;gap:2px;width:20px;height:20px;padding-bottom:2px;border-bottom:1px solid var(--gold-light)}.mark i{display:block;width:4px;background:var(--gold-light)}.mark i:first-child{height:7px}.mark i:nth-child(2){height:13px}.mark i:last-child{height:18px}.nav-proof{display:flex;align-items:center;gap:9px;margin-left:auto;color:rgba(238,233,220,.7);font:700 8px/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.17em}.nav-proof span{width:6px;height:6px;border-radius:50%;background:var(--orange);box-shadow:0 0 0 4px rgba(233,120,53,.12)}.nav-rule{width:44px;height:1px;margin-left:22px;background:rgba(238,233,220,.35)}
.content{position:absolute;z-index:4;left:clamp(28px,8.3vw,132px);top:50%;width:min(46%,550px);transform:translateY(-44%)}.kicker{display:flex;align-items:center;gap:10px;margin-bottom:21px;color:#d9c28c;font:700 9px/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.18em}.live-dot{display:block;width:7px;height:7px;border:1px solid #f4b651;border-radius:50%;box-shadow:0 0 0 5px rgba(244,182,81,.12);animation:pulse 2.3s infinite}@keyframes pulse{50%{box-shadow:0 0 0 9px rgba(244,182,81,0);opacity:.55}}h1{margin:0;color:#eee9dd;font-family:Georgia,"Times New Roman",serif;font-weight:400;font-size:clamp(47px,5.1vw,78px);line-height:.91;letter-spacing:-.067em;text-wrap:balance;text-shadow:0 15px 50px rgba(0,0,0,.16)}h1 em{color:#f0c16d;font-style:italic}h1 span{position:relative;color:#dce6de}h1 span:after{content:"";position:absolute;left:3px;right:-5px;bottom:-7px;height:1px;background:linear-gradient(90deg,var(--orange),transparent);transform:rotate(-1.5deg)}.lede{max-width:400px;margin:26px 0 16px;color:#c3cfce;font:400 14px/1.68 ui-sans-serif,system-ui,sans-serif;letter-spacing:.006em}.motto{display:flex;align-items:center;gap:10px;margin:0 0 23px;color:#e6bd6a}.motto span{font:600 16px/1 Georgia,"Noto Serif Devanagari",serif;letter-spacing:.04em}.motto i{display:block;width:28px;height:1px;background:rgba(230,189,106,.58)}.motto small{color:rgba(221,225,207,.53);font:700 7px/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.14em}.actions{display:flex;align-items:center;gap:17px}#enter{display:flex;align-items:center;gap:18px;border:0;border-radius:0;padding:16px 15px 16px 21px;color:#1a2939;background:linear-gradient(135deg,#f1cf81,#d8a64c);box-shadow:0 13px 30px rgba(0,0,0,.2);font:800 10px/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.15em;cursor:pointer;transition:transform .25s ease,box-shadow .25s ease,filter .25s ease}#enter i{display:grid;width:23px;height:23px;place-items:center;border:1px solid rgba(20,34,49,.45);border-radius:50%;font:400 16px/1 Arial;font-style:normal;transition:transform .25s ease}#enter:hover{transform:translateY(-4px);filter:brightness(1.1);box-shadow:0 20px 37px rgba(0,0,0,.3)}#enter:hover i{transform:rotate(45deg)}.microcopy{padding-left:15px;border-left:1px solid rgba(238,233,220,.28);color:#bac9cc;font:700 8px/1.55 ui-monospace,SFMono-Regular,monospace;letter-spacing:.13em}
.statue-stage{position:absolute;z-index:2;right:clamp(-80px,1vw,18px);top:72px;width:min(56%,710px);height:710px;perspective:1500px;transform-style:preserve-3d}.halo{position:absolute;z-index:-1;right:7%;top:14%;width:470px;height:470px;border:1px solid rgba(243,205,121,.23);border-radius:50%;box-shadow:0 0 0 34px rgba(239,202,116,.022),0 0 0 98px rgba(239,202,116,.015),inset 0 0 90px rgba(244,192,84,.12);animation:halo-turn 24s linear infinite}.halo:before,.halo:after{content:"";position:absolute;inset:13px;border:1px dashed rgba(235,207,147,.34);border-radius:50%}.halo:after{inset:70px;border-style:solid;border-color:rgba(188,211,212,.12)}@keyframes halo-turn{to{transform:rotate(360deg)}}.orbit{position:absolute;z-index:2;right:-2%;top:45%;width:610px;height:210px;border:1px solid rgba(226,186,101,.4);border-radius:50%;transform:rotate(-11deg) rotateX(66deg);pointer-events:none}.orbit:before{content:"";position:absolute;left:17%;top:-3px;width:9px;height:9px;border-radius:50%;background:#f6d680;box-shadow:0 0 16px 5px rgba(246,214,128,.45);animation:orbit-dot 5.8s linear infinite}@keyframes orbit-dot{to{transform:translateX(390px) translateY(125px)}}.orbit-back{opacity:.5;top:38%;transform:rotate(16deg) rotateX(64deg);animation:drift 8s ease-in-out infinite}.orbit-front{opacity:.55;top:56%;border-color:rgba(172,213,203,.25);animation:drift 9s -3s ease-in-out infinite reverse}@keyframes drift{50%{margin-right:14px;opacity:.22}}.gold-beam{position:absolute;z-index:-1;width:1px;height:510px;right:43%;top:14%;background:linear-gradient(transparent,rgba(242,201,112,.4),transparent);transform:rotate(29deg);transform-origin:bottom;opacity:.7}.beam-two{right:14%;top:26%;height:380px;opacity:.32;transform:rotate(-19deg)}
.statue-card{position:absolute;z-index:1;right:1%;top:4px;width:570px;height:704px;transform-style:preserve-3d;will-change:transform;animation:hero-float 7.5s ease-in-out infinite}.statue-card:before{content:"";position:absolute;z-index:-1;left:16%;top:15%;width:67%;height:68%;border-radius:50%;background:radial-gradient(ellipse,rgba(246,203,108,.26),rgba(89,136,154,.1) 40%,transparent 68%);filter:blur(18px);transform:translateZ(-80px)}@keyframes hero-float{0%,100%{transform:translate3d(0,0,0) rotateY(-7deg) rotateX(1deg)}50%{transform:translate3d(-8px,-13px,22px) rotateY(7deg) rotateX(-2deg)}}#justice{position:absolute;z-index:2;right:0;top:0;width:100%;height:100%;object-fit:contain;object-position:center;filter:drop-shadow(18px 28px 22px rgba(1,8,16,.42)) saturate(1.04) contrast(1.02);transform:translateZ(32px);user-select:none;-webkit-user-drag:none}.statue-shadow{position:absolute;z-index:0;right:16%;bottom:7px;width:60%;height:60px;border-radius:50%;background:rgba(1,7,14,.5);filter:blur(21px);transform:rotateX(69deg) translateZ(-40px)}.scanline{position:absolute;z-index:4;left:13%;right:14%;top:14%;height:1px;background:linear-gradient(90deg,transparent,rgba(255,225,152,.9),transparent);box-shadow:0 0 16px rgba(255,218,133,.85);opacity:.45;mix-blend-mode:screen;animation:scanner 5.7s ease-in-out infinite}@keyframes scanner{0%,20%{transform:translateY(0);opacity:0}30%,72%{opacity:.45}85%,100%{transform:translateY(460px);opacity:0}}
.focus-tag,.scale-tag{position:absolute;z-index:4;display:flex;align-items:center;gap:9px;color:#d8e1d6;font:700 8px/1.45 ui-monospace,SFMono-Regular,monospace;letter-spacing:.14em}.focus-tag{right:4%;bottom:93px;padding:11px 12px;border:1px solid rgba(228,233,216,.25);background:rgba(22,40,57,.46);backdrop-filter:blur(9px)}.focus-icon{color:#efbd62;font-size:14px}.scale-tag{left:8%;top:27%;padding-left:12px;border-left:1px solid rgba(237,195,105,.75)}.scale-tag i{width:31px;height:1px;background:linear-gradient(90deg,#e9b95e,transparent)}.scale-tag b{color:#ebbe6b}
.footer-line{position:absolute;z-index:8;bottom:0;left:0;right:0;display:flex;align-items:center;justify-content:space-between;height:43px;padding:0 clamp(26px,5.2vw,80px);border-top:1px solid rgba(229,224,211,.13);color:rgba(219,228,218,.56);font:700 8px/1 ui-monospace,SFMono-Regular,monospace;letter-spacing:.13em}.footer-line span{color:#e2b75e}.footer-center{color:rgba(219,228,218,.32)}
.depart .content,.depart .nav,.depart .footer-line{opacity:0;transform:translateX(-30px);transition:opacity .3s ease,transform .45s ease}.depart .statue-stage{animation:takeover .72s cubic-bezier(.6,0,.9,.15) forwards}@keyframes takeover{to{transform:scale(2.6) translateX(-9%) rotateY(-12deg);filter:brightness(1.8) blur(1px);opacity:0}}@media(max-width:850px){#landing{height:760px}.nav-proof,.nav-rule,.footer-center{display:none}.statue-stage{right:-135px;top:38px;width:600px;opacity:.71}.statue-card{width:480px;height:620px}.content{z-index:6;left:28px;top:auto;bottom:86px;width:calc(100% - 56px);transform:none}.lede{max-width:370px}.footer-line{padding:0 27px}.focus-tag,.scale-tag{display:none}}@media(max-width:520px){#landing{height:700px}.nav{height:70px;padding:0 22px}.wordmark{font-size:13px}.statue-stage{right:-205px;top:45px;opacity:.56}.statue-card{width:470px;height:605px}.content{left:22px;bottom:67px;width:calc(100% - 44px)}.kicker{font-size:7px;margin-bottom:14px}h1{font-size:49px}.lede{max-width:320px;margin:18px 0 20px;font-size:12px;line-height:1.55}.microcopy{display:none}.footer-line{height:35px;padding:0 21px;font-size:6px}.footer-line>div:last-child{display:none}.sunrise{right:-270px;top:-30px}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
</style>
<script>
(()=>{const root=document.getElementById('landing'),enter=document.getElementById('enter'),card=document.getElementById('statue-card'),canvas=document.getElementById('aurora'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const openWorkspace=()=>{if(root.classList.contains('depart'))return;root.classList.add('depart');setTimeout(()=>{try{const button=[...window.parent.document.querySelectorAll('button')].find(item=>item.innerText.trim()==='Open Nyaya AI');if(button){button.click();return}}catch(_){}try{window.top.location.assign('/?enter=1')}catch(_){window.location.assign('/?enter=1')}},590)};enter.addEventListener('click',openWorkspace);root.addEventListener('pointermove',event=>{if(reduced)return;const x=(event.clientX/window.innerWidth-.5)*2,y=(event.clientY/window.innerHeight-.5)*2;card.style.animation='none';card.style.transform=`translate3d(${x*-7}px,${y*-5}px,${18+Math.abs(x)*15}px) rotateY(${-7+x*8}deg) rotateX(${1-y*4}deg)`});root.addEventListener('pointerleave',()=>{if(reduced)return;card.style.transform='';card.style.animation=''});const ctx=canvas.getContext('2d');if(!ctx)return;let dots=[],width=0,height=0;function resize(){const scale=Math.min(devicePixelRatio||1,2);width=canvas.clientWidth;height=canvas.clientHeight;canvas.width=width*scale;canvas.height=height*scale;ctx.setTransform(scale,0,0,scale,0,0);dots=Array.from({length:Math.max(32,Math.floor(width/24))},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.35+.25,v:Math.random()*.18+.03,a:Math.random()*.36+.08,gold:Math.random()>.74}))}new ResizeObserver(resize).observe(canvas);resize();function draw(){ctx.clearRect(0,0,width,height);for(const dot of dots){dot.y-=dot.v;if(dot.y<-5){dot.y=height+5;dot.x=Math.random()*width}ctx.beginPath();ctx.arc(dot.x,dot.y,dot.r,0,Math.PI*2);ctx.fillStyle=dot.gold?`rgba(239,192,98,${dot.a})`:`rgba(205,225,223,${dot.a})`;ctx.fill()}if(!reduced)requestAnimationFrame(draw)}draw()})();
</script>
"""
